### ISSUE TITLE
Pause deposits on maxDepositSubTree

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#19]
We should stop accepting deposits once we have achieved max number of deposits.

**Comment by barryWhiteHat** [comment]
Here could we make a second subtree that we start to fill up? 

I don't want deposits to fail and have to be redone.

**Comment by vaibhavchellani** [comment]
I see, yeah that makes sense, but I think we will need to have a queue of several subtrees, in that case, only having 2 doesn't solve the problem.

**Comment by vaibhavchellani** [comment]
Will add this while doing rollback deposits: https://github.com/Hubble-Project/contracts/issues/2#issuecomment-645300235
