### ISSUE TITLE
Add param related events

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#21]
The coordinator node watches the contracts for some specific events like
- MaxDepositSubTree
- StakeAmount
- MaxDepth

We need to add events that the coordinator can monitor

**Comment by vaibhavchellani** [comment]
We need to connect logger contract to the governance contract. Such that whenever any of the parameters is changed an event is emitted which emits the event containing `oldValue, newValue`. 

Governance contract with all the values is present here: https://github.com/Hubble-Project/contracts/blob/master/contracts/Governance.sol

**Comment by barryWhiteHat** [comment]
We can side step this if we force coordinators to updat etheir node when the governance changes the contract param.

**Comment by vaibhavchellani** [comment]
It's better we do it this way, will save several network calls for full/watcher nodes as well. Not an urgent issue atm, but something that will help later.

**Comment by ChihChengLiang** [comment]
Let's consolidate this with https://github.com/thehubbleproject/hubble-contracts/issues/320
