### ISSUE TITLE
Remove usage of pragma experimental 

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#37]
Right now a lot of contracts use the experimental features of solidity for convenience but we def cant go with experimental features and should start looking into minimise and/or remove their usage from the codebase.

**Comment by thrilok209** [comment]
![Screenshot_20200609-005442__01](https://user-images.githubusercontent.com/22830915/84382004-9010f380-ac07-11ea-95f8-9a61c78e68e0.jpg)
pragma experimental ABIEncoderV2 will not throw warning on solidity version v0.6.0 and above.

**Comment by thrilok209** [comment]
![image](https://user-images.githubusercontent.com/22830915/84382319-13cae000-ac08-11ea-948f-2bd405189e86.png)
pragma experimental ABIEncoderV2 won't throw a warning in the latest solidity version v0.6.0 and above.

**Comment by vaibhavchellani** [comment]
Great!

**Comment by ChihChengLiang** [comment]
Can close in favor of https://github.com/thehubbleproject/hubble-contracts/issues/319
