### ISSUE TITLE
Slash when accounts in transaction do not exist

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#44]
We need to add a condition to ensure that the coordinator gets slashed if the transaction contains an account which doesn't exist and hence it's impossible to create an Merkel proof for it

**Comment by barryWhiteHat** [comment]
It should be possible to create merkle proofs for all indexes in the account tree. The tree should be initalized with 0 fro all leaves so you can always load an index at position x.

**Comment by vaibhavchellani** [comment]
Yeah, that's possible. 

Consider this:
1. User signs a transaction with from index as 100 while the max index created was 50
2. Coordinator submits the transaction

At the moment the `processTx` function tries to:
- Verify the public key is present via the PDA Merkle proof provided by the challenger

We need to find a way to somehow let the challenger indicate that the `fromIndex` doesn't exist and here's the MP that shows that the `accountTree` committed doesn't have a `fromIndex` mentioned in the transaction.

**Comment by barryWhiteHat** [comment]
Agree you cannot have index gr8er than max index. 

``` require(index >= max_index)```

where max index as a variable we incrament every time a new address is added to the pda tree?

**Comment by vaibhavchellani** [comment]
Yeah, we do have that variable but it's not part of the commitment. So it keeps changing.

**Comment by vaibhavchellani** [comment]
One expensive way to deal with this would be, sending 2 PDA MP's which proves there exists 2 leaves with indexes `n` and `n+1` where `n` is not `zero` while `n+1` is zero. Thus proving `n` was the max_index

**Comment by barryWhiteHat** [comment]
> Yeah, we do have that variable but it's not part of the commitment. So it keeps changing.

It only incraments so there is no way for `require(index >= max_index)` to be true and then later false. index only gets bigger so if `require(index >= max_index)` is true then `require(index+1 >= max_index)`

**Comment by ChihChengLiang** [comment]
We don't have to worry about this now. The public key Id will be passed into the `MerkleTree.verify()` as the path parameter, which will break nothing given all any possible `path`. It's also cryptographically impossible to create a valid proof out of a path outside of the tree. So no extra check required. 

Can close this issue
