### ISSUE TITLE
Calling a function that takes a struct as input from truffle test fails

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#57]
Right now calling functions in `rollup-utils` reverts from truffle test and I have to write deconstructed functions to just check. However, the functions work well when some other contract calls those.

**Comment by ChihChengLiang** [comment]
I guess this is the place you are talking about. We want to pass a transaction object to the compressTx function but it reverted for invalid input.

https://github.com/thehubbleproject/contracts/blob/a27ba891419d2cf040030af0ed4f7f4e74b9c596/scripts/helpers/utils.ts#L209-L210
Uncommented the above code gets `Returned error: VM Exception while processing transaction: revert`


What I learned so far is the following code and input works on remix.ethereum.org even with my local ganache as the provider.

```solidity
pragma solidity ^0.5.15;
pragma experimental ABIEncoderV2;

contract Example {
        struct Transaction {
            uint256 fromIndex;
            uint256 toIndex;
            uint256 tokenType;
            uint256 nonce;
            uint256 txType;
            uint256 amount;
            bytes signature;
        }
        function CompressTx(Transaction memory _tx) public pure returns (Transaction memory){
            return _tx;
        }
}
```
input `[2, 3, 1, 1, 1, 1, "0x1ad4773ace8ee65b8f1d94a3ca7adba51ee2ca0bdb550907715b3b65f1e3ad9f69e610383dc9ceb8a50c882da4b1b98b96500bdf308c1bdce2187cb23b7d736f1b"]`

So I guess it's a truffle specific problem.

**Comment by vaibhavchellani** [comment]
Yeah, this is what I am taking about. I think its a typechain+ truffle fault. Things work for me when I call these functions from golang.

**Comment by vaibhavchellani** [comment]
Closing this for now and suggest people use the deconstructed functions in the rollup-utils.sol file and use the non-deconstructed ones from the contracts.
