### ISSUE TITLE
Use processBatch more effectively

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#69]
Right now we aren't using processBatch anywhere on the node, I am struggling to think of any compelling place to use it. This issue is to discuss its usage.

**Comment by vaibhavchellani** [comment]
We aren't using it on the node atm because I will have to create witnesses for all transactions before calling this function, one benefit of using `processBatch` once and not `processTx` on every transaction would be reduced network calls.

**Comment by barryWhiteHat** [comment]
We could use it as a final check to make sure the blcok created is correct. 

Will we use processBatch when syncing ?

**Comment by vaibhavchellani** [comment]
We could use processBatch while syncing, but we will have to create witnesses for all txs before that.

The process would look something like this:
1. Get submitBatch calldata
2. Loop through txs
3. Create MP for from account, apply tx on fromAccount
4. Create MP for to account, apply tx on toAccount
5. Do this for all txs
6. Call processBatch with all the witnesses to validate batch

If we use processTx the process would look something like:
1. Get submitBatch calldata
2. Loop through txs
3. Create MP for from account, apply tx on fromAccount
4. Create MP for to account, apply tx on toAccount
6. Call processTx with all the witnesses to validate tx
7. Post doing this for all txs, match final state root.

**Comment by ChihChengLiang** [comment]
Let's bring the discussion to the node side. https://github.com/thehubbleproject/hubble-commander/issues/55
