### ISSUE TITLE
Use eth-waffle solidity mocks

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#74]
Currently writing tests is not a lot of fun because it takes a lot of time to deploy contract and debug. We are exploring options at the moment and the one that stands out is `eth-waffle` using which we could mock contracts as given [here](https://medium.com/ethworks/mocking-solidity-smart-contracts-with-waffle-55813b22ebf2). 

This issue is to track progress and discussions on how to improve testing framework in hubble-core

**Comment by vaibhavchellani** [comment]
Also it would be interesting to use [fixtures](https://ethereum-waffle.readthedocs.io/en/latest/fixtures.html) from eth-waffle too!

**Comment by vaibhavchellani** [comment]
Still researching what might be the best and least dev intensive way to handle this.

**Comment by ChihChengLiang** [comment]
My current workaround is using `npx truffle development`.
Run `migrate --reset`, load deployed contract, then run the contract function.
It makes iterating a single function faster.

**Comment by vaibhavchellani** [comment]
We also have in works test specific migrations, but we found that to be very dev intensive. We can use it for quick iterations tho

**Comment by ChihChengLiang** [comment]
We have waffle now, can close.
