### ISSUE TITLE
Upgrade solidity version to 0.6

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#8]

**Comment by vaibhavchellani** [comment]
Updated to 0.5.15

**Comment by ChihChengLiang** [comment]
I heard 0.7 compiles to gas-saving bytecodes and 0.8 has a native overflow check. Worth trying.

**Comment by ChihChengLiang** [comment]
Created issue here https://github.com/thehubbleproject/hubble-contracts/issues/319
