### ISSUE TITLE
Tx compression for transfer

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#83]
We need to add some actual compression for txs that are submitted via submitBatch as `calldata`, currently, they are only abi encoded. 

The only change we expect are in the functions `compressTx`, `compressTxWithMessage` and `DecompressTx` in [RollupUtils](https://github.com/thehubbleproject/contracts/blob/master/contracts/libs/RollupUtils.sol)

The node will automatically start sending compressed transactions once this issue is closed!

**Comment by ChihChengLiang** [comment]
done
