### ISSUE TITLE
Update submit batch to create MT root optimistically

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/contracts#98]
Right now we submit txs in plain text using call data and we merkalise the `calldata` on-chain in order to "commit" the txs.

Correctly pointed out by @kilic we can commit the hash of `txs` and accept the merkleRoot of transactions from the coordinator.Along with this our fraud proof will check if the Merklize(calldata) == merkleRoot stored in the commitment. 

Currently the batch looks like:
```
batch = {
stateRoot: 0x0000...,
txRoot: 0x0001....
}
```

Which will be changed to: 
```
batch = {
stateRoot: 0x0000...,
txRoot: 0x0001....,
txCommitted: 0x000111...
}
```

**Comment by kilic** [comment]
* Maybe don't even use txRoot for batches where txRoot is not useful of anything
* Now it seems like Tx root is only useful for withdraws so taht for Transfer batches
* Also we definitely need txCommit = hash(tx_arr)  in a reachable path on-chain for cheaper proof processing

**Comment by ChihChengLiang** [comment]
This is outdated. We don't have tx root now. We don't have hash(tx_arr) too, transactions are already in compression form. The compressed transactions have to be submitted to the fraud-proof as a whole too, no point to submit an additional hash of transactions.

**Comment by vaibhavchellani** [comment]
Yeah very outdated now.
